# Generated by Django 3.0.3 on 2020-02-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourth_third_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
